[Modal]: Closes #215 created Save Deadline button
zurichat/zc_plugin_reminder pull request #279
Opened 2021-09-02 14:24 UTC by adetobaadedeji

This PR Closes #215

2021-09-02 16:43 UTC, a11rew requested changes
Component looks good. Good job on adding the breakpoints as well.

- Update the absolute pixel values to percentages
- Remove the enclosing div and return just the button. The button will then be enclosed in a div in the newDeadline index so resizing and responsiveness is centralized.

2021-09-02 16:43 UTC, a11rew commented
Closing this. Reopen it when updated

2021-09-03 14:33 UTC, a11rew approved these changes

2021-09-03 14:34 UTC, merged

2021-09-06 11:36 UTC, adetobaadedeji commented
Live Link: http://reminders.zuri.chat

Issue Link: Issue Link
https://github.com/zurichat/zc_plugin_reminder/issues/215