Due date picker
zurichat/zc_plugin_reminder pull request #292
Opened 2021-09-02 18:15 UTC by literallymarvellous

2021-09-02 19:15 UTC, a11rew requested changes
Remove the packages you added. Install the prettier vscode extension. Create state in the component to hold the date picker values.

2021-09-03 12:40 UTC, a11rew commented
Looks good. Moved the component to the createDeadline folder. Link the issue you're closing and your PR is ready for merge.

2021-09-03 12:54 UTC, literallymarvellous commented
Issue: https://github.com/zurichat/zc_plugin_reminder/issues/207

2021-09-03 14:07 UTC, a11rew approved these changes

2021-09-03 14:07 UTC, merged