#203 Display Avatar of users assigned to a task
zurichat/zc_plugin_reminder pull request #323
Opened 2021-09-03 18:59 UTC by odaisaac

#### Reference Issue/PRs
#### #203 Display Avatar of users assigned to a task
#### All errors on previous pull request resolved encountered error so need to re-clone and create a new branch thanks I hope to my changes pass

2021-09-04 01:35 UTC, a11rew requested changes
This is good, you're close. 
- Update the images so they resize to fit in the parent container. 
- Use percentages in your `-space-x` styles so the overlaps work at any screen size. Extend the tailwind config percentage scale to include percentages. See how [here](https://tailwindcss.com/docs/space#spacing-scale)

2021-09-04 05:03 UTC, odaisaac commented
Okay will work on it thanks

On Sat, 4 Sep 2021, 2:35 am Andrew Glago, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> This is good, you're close.
>
>    - Update the images so they resize to fit in the parent container.
>    - Use percentages in your -space-x styles so the overlaps work at any
>    screen size. Extend the tailwind config percentage scale to include
>    percentages. See how here
>    <https://tailwindcss.com/docs/space#spacing-scale>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zurichat/zc_plugin_reminder/pull/323#pullrequestreview-746529011>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVI34LJQ6EO5NYWP4GWWX73UAFZWFANCNFSM5DMJTJBQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-05 00:18 UTC, a11rew approved these changes

2021-09-05 00:19 UTC, merged

2021-09-05 07:49 UTC, odaisaac commented
So sorry boss for the late commit I already have the new changes that has correct previous issues can I still send it in my pc power yesterday night is down and am unable to commit the changes if chanced pls I wish to commit the changes spend alot of time on it making it responsive