designed dropdown component for company plugin
zurichat/zc_plugin_reminder pull request #328
Opened 2021-09-03 21:01 UTC by godswilludoh

[dropdown]:Fixes #196 (designed dropdown component for company plugin)

2021-09-04 02:03 UTC, a11rew requested changes
- Use tailwind classes instead of the style object.
- Update the component to get the assignee options from props
- The dropdown component should let you type in an assignee name and show you the closest match. Like auto suggestions on google. That's required to close the issue

2021-09-04 13:42 UTC, a11rew commented
Request a review when done

2021-09-05 00:21 UTC, jutivia approved these changes

2021-09-05 00:22 UTC, jutivia approved these changes

2021-09-05 00:28 UTC, a11rew approved these changes

2021-09-05 00:29 UTC, merged